using System.Text.RegularExpressions;

namespace ZenithUI.Tests.Theming;

/// <summary>
/// Guards <c>tailwind/zenith.theme.css</c> — the file a consuming application imports into its own
/// Tailwind build, generated by <c>tools/build-theme.mjs</c> and shipped in the package.
/// </summary>
/// <remarks>
/// <para>
/// Nothing else in the suite can catch a regression here. The library's own stylesheet is built
/// from <c>Styles/</c> and stays correct however badly the generator misbehaves; the failure shows
/// up only in a <i>different</i> project's build, which is exactly the place a component library
/// cannot test from.
/// </para>
/// <para>
/// The three properties asserted below are the three ways the artifact can be wrong while still
/// looking like a stylesheet: a stale copy missing a token that was added to
/// <c>Styles/tokens/theme.css</c>; a relative <c>@import</c> that resolves in this repository and
/// nowhere else once the file has been copied into a consumer's <c>obj/</c>; and an empty
/// candidate sweep, which compiles fine and silently reopens the cascade-order trap.
/// </para>
/// </remarks>
public partial class ConsumerThemeTests
{
    private static readonly string Theme = File.ReadAllText(
        Path.Combine(AppContext.BaseDirectory, "Tailwind", "zenith.theme.css"));

    private static readonly string Source = File.ReadAllText(
        Path.Combine(AppContext.BaseDirectory, "Tokens", "theme.css"));

    [Fact]
    public void Theme_CarriesEveryTailwindThemeVariable()
    {
        var declared = ThemeVariable().Matches(Source).Select(m => m.Groups[1].Value).ToArray();

        declared.ShouldNotBeEmpty("Styles/tokens/theme.css declares no @theme variables at all.");

        foreach (var variable in declared)
        {
            Theme.Contains($"{variable}:", StringComparison.Ordinal).ShouldBeTrue(
                $"'{variable}' is declared in Styles/tokens/theme.css but absent from the generated " +
                "tailwind/zenith.theme.css. A consuming application's own Tailwind build would not " +
                "compile the utility it backs. Re-run `npm run css:build` in src/ZenithUI.");
        }
    }

    [Fact]
    public void Theme_IsFlattened()
    {
        // Comments may show a consumer what to write; a real @import would point at a path that
        // exists only in this repository, and the file is consumed from the consumer's obj/.
        var imports = Uncommented(Theme)
            .Split('\n')
            .Where(line => line.TrimStart().StartsWith("@import", StringComparison.Ordinal))
            .ToArray();

        imports.ShouldBeEmpty(
            "tailwind/zenith.theme.css must be self-contained: it is copied out of the package " +
            "into a consuming project, where a relative import resolves to nothing.");
    }

    [Fact]
    public void Theme_DeclaresTheCandidatesTheLibrarysOwnMarkupUses()
    {
        var candidates = SourceInline().Matches(Theme).Select(m => m.Groups[1].Value).ToHashSet(StringComparer.Ordinal);

        // A structural utility, a responsive one and a state one. None is in the safelist - each
        // can only be here because the scanner read the components - and each is the kind that
        // breaks a consumer's page when only one of the two stylesheets emits it.
        foreach (var candidate in new[] { "appearance-none", "size-4", "sm:px-6" })
        {
            candidates.ShouldContain(candidate,
                $"'{candidate}' appears in ZenithUI's markup but not in the generated theme. A " +
                "consuming application's stylesheet would then omit a rule ZenithUI's contains, " +
                "and within a cascade layer the later sheet wins - see docs/theming.md.");
        }

        // The safelist is concatenated in whole, so the semantic surface travels with it.
        candidates.ShouldContain("ring-ring");
    }

    private static string Uncommented(string css) => Comment().Replace(css, string.Empty);

    [GeneratedRegex(@"^\s*(--(?:color|radius|shadow|spacing)-[a-z0-9-]+)\s*:", RegexOptions.Multiline)]
    private static partial Regex ThemeVariable();

    [GeneratedRegex(@"@source\s+inline\(""([^""]+)""\)")]
    private static partial Regex SourceInline();

    [GeneratedRegex(@"/\*.*?\*/", RegexOptions.Singleline)]
    private static partial Regex Comment();
}
