/*
 * Generates tailwind/zenith.theme.css - the file a consuming application imports into ITS OWN
 * Tailwind entry point.
 *
 * Why this file has to be generated rather than shipped as-is
 * ----------------------------------------------------------
 * Two distinct problems, one artifact.
 *
 *  1. `@theme`. A utility is compiled by the build that scans the markup using it. ZenithUI's
 *     precompiled stylesheet carries `bg-surface` for ZenithUI's markup; it cannot carry it for
 *     the consumer's. Their build needs the `@theme inline` block, and a NuGet package is not
 *     something Tailwind can `@import` by name - hence a single flattened file, copied next to
 *     their project by build/ZenithUI.targets.
 *
 *  2. Cascade order. The library's sheet and the consumer's sheet both write into the `utilities`
 *     layer, and within a layer the later file wins. The consumer's build emits only what THEY
 *     use, so `.flex` is almost certainly in their sheet and `.lg\:hidden` almost certainly is
 *     not - and a library component written `class="flex lg:hidden"` is then `display: flex` at
 *     every width. Telling the consumer's build about every candidate ZenithUI's own markup
 *     contains makes both sheets emit the same rules, so which one lands last stops mattering.
 *
 * The candidate list comes from @tailwindcss/oxide - the same scanner Tailwind itself runs - so
 * it cannot drift from what the library's stylesheet was built with. Strings that are not valid
 * utilities are inert: Tailwind emits nothing for a candidate it cannot parse.
 */

import { Scanner } from "@tailwindcss/oxide";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const project = join(dirname(fileURLToPath(import.meta.url)), "..");
const styles = join(project, "Styles");

/** The same sources the library's own stylesheet is built from - see Styles/zenith.css. */
const sources = [
  { base: join(project, "Components"), pattern: "**/*.razor", negated: false },
  { base: join(project, "Core"), pattern: "**/*.cs", negated: false },
  { base: join(project, "Services"), pattern: "**/*.cs", negated: false },
];

/*
 * `@source inline(...)` treats its argument as a brace-expansion pattern, so a candidate
 * carrying `{`, `}`, a quote or whitespace would be read as syntax rather than as a class name.
 * Custom property names and pure punctuation are dropped because neither can ever be a utility.
 */
const usable = (candidate) =>
  candidate.length > 0 &&
  !candidate.startsWith("--") &&
  !/[{}"'\s\\]/.test(candidate) &&
  /[a-zA-Z0-9]/.test(candidate);

const candidates = [...new Set(new Scanner({ sources }).scan().filter(usable))].sort();

const theme = readFileSync(join(styles, "tokens", "theme.css"), "utf8");
const safelist = readFileSync(join(styles, "safelist.css"), "utf8");

const header = `/*
 * ZenithUI theme - for a consuming application that runs its own Tailwind build.
 *
 * GENERATED by tools/build-theme.mjs. Do not edit; edit Styles/tokens/theme.css,
 * Styles/safelist.css or the components instead.
 *
 * Import it from your own Tailwind entry point so that ZenithUI's semantic utilities
 * (bg-surface, text-content-muted, rounded-zen-lg, the zen-dark: variant) compile for YOUR
 * markup too:
 *
 *     @import "tailwindcss";
 *     @import "../obj/zenithui/zenith.theme.css";
 *
 * The path is where build/ZenithUI.targets drops this file inside your project - see
 * docs/theming.md. Nothing here emits a colour value: the palette arrives at runtime from
 * _content/ZenithUI/zenith.css, and every utility below resolves a --zen-* custom property, so
 * overriding one in your own stylesheet rebrands the library with no rebuild of the package.
 *
 * Generated from ${candidates.length} scanned candidates.
 */

`;

const inlined = `/*
 * ---- ZenithUI's own utility surface --------------------------------------------------------
 *
 * Every candidate the library's markup contains, so that your sheet and ZenithUI's agree on
 * what a shared utility means regardless of which one the browser parses last. Tailwind emits
 * nothing for the entries that are not utilities.
 */

${candidates.map((candidate) => `@source inline("${candidate}");`).join("\n")}
`;

mkdirSync(join(project, "tailwind"), { recursive: true });

writeFileSync(
  join(project, "tailwind", "zenith.theme.css"),
  [header, theme, "\n", safelist, "\n", inlined].join(""),
  "utf8",
);

console.log(`zenith.theme.css: ${candidates.length} candidates`);
